development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: albums_development
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: albums_test
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: albums_production
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock

cucumber:
  <<: *test